In [1]:
import numpy as np

Сравнение скорости между NumPy array и Python List(Список):

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(100000))

In [7]:
my_arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Умноженим каждый элемент на 2 и сравним время выполнения этой операции:

In [16]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 11.7 ms, sys: 3.62 ms, total: 15.3 ms
Wall time: 13.5 ms


In [17]:
%time for _ in range(10): my_list2 = [ x*2 for x in my_list]

CPU times: user 61.2 ms, sys: 7.63 ms, total: 68.8 ms
Wall time: 67.8 ms


In [18]:
my_arr2[:10]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
my_list2[:10]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

Как мы видим, работать с Numpy Array намного быстрее, чем со списками Питона.

# <center> NumPy N-dimentional Array<center>
  
   

# <center> NumPy Массив с N измерениями(осями) <center>

Ndarray - контейнер для хранения огромного кол-ва данных в Питоне.
<hr>

Сгенерируем рандомный датасет:

In [22]:
data = np.random.randn(2,3) # ndarray размером 2 на 3 

In [23]:
data

array([[ 0.08867146,  0.3163277 ,  1.0746514 ],
       [-0.29307782,  0.1271677 ,  0.22676498]])

Теперь мы можем манипулировать этот датасет.<br>

Умножим каждое число в датасете на 100:

In [27]:
data * 100

array([[  8.86714551,  31.63276951, 107.46514025],
       [-29.30778247,  12.71677029,  22.67649802]])

In [28]:
data + data

array([[ 0.17734291,  0.63265539,  2.1493028 ],
       [-0.58615565,  0.25433541,  0.45352996]])

Размер датасета:

In [32]:
data.shape

(2, 3)

Тип данных в датасете:

In [33]:
data.dtype

dtype('float64')

Создание ndarray:

Самый простой способ - использовать _array_ function.

In [34]:
data1 = [54, 12.5, 77, 16]

In [35]:
arr1 = np.array(data1)

In [36]:
arr1

array([54. , 12.5, 77. , 16. ])

In [37]:
arr1.shape

(4,)

In [38]:
arr1.dtype

dtype('float64')

Другой пример, больше чем одна ось:

In [46]:
data2 = [[15,1212,4], [643, 11, 12 ]]

In [47]:
arr2 = np.array(data2)

In [48]:
arr2

array([[  15, 1212,    4],
       [ 643,   11,   12]])

In [49]:
arr2.ndim # число измерений 

2

Сравним типы данных:

In [50]:
arr1.dtype

dtype('float64')

In [51]:
arr2.dtype

dtype('int64')

Встроенные функции для создавания новых ndarray: 

Ndarray только из единиц(np.ones) или только из нулей(np.zeros), нужно только указать измерения:

In [53]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

arange тоже самое, что range в Питоне, возвращает диапозон чисел:

In [80]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [81]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

Создание Единичной Матрицы(квадратная матрица, элементы главной диагонали которой равны единице поля, а остальные равны нулю):

In [86]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

full - создает ndrarray с любом размером(shape) и любом числом внутри(fill_value): 

In [93]:
np.full(shape=(4,5), fill_value=24)

array([[24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24]])

Не обязательно указывать параметры, главное соблюдать последовательность:

In [96]:
np.full((4,5), 24)

array([[24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24]])

# <center> Типы Данных для Ndarray <center>

Типы данных, метаданные - данные о данных(информация о другой информации):

In [98]:
arr1 = np.array([1,3,4], dtype=np.float64)

In [99]:
arr2 = np.array([1,3,4], dtype=np.int32)

In [102]:
arr1.dtype

dtype('float64')

In [103]:
arr2.dtype

dtype('int32')

NumPy содержит большое число типов данных, например: bool_, character, int_, int8, int16, int32, int64, float_, float8, float16, float32, float64, complex_, complex64, object_.


# <center> Конвертация<center>

In [112]:
arr1 = np.array([-1.532, 6.454, 3.22])

In [113]:
arr1

array([-1.532,  6.454,  3.22 ])

In [114]:
arr1_int = arr1.astype(np.int32)

In [115]:
arr1_int

array([-1,  6,  3], dtype=int32)

In [121]:
arr1_str = arr1.astype(np.str)

In [125]:
arr1_str

array(['-1.532', '6.454', '3.22'], dtype='<U32')

Конвертировать можно тогда, когда это имеет смысл. Мы не можем конвертировать текст в целое число.

In [131]:
arr1 = np.array(["привет", "пока"])

In [132]:
arr1.astype(np.int)

ValueError: invalid literal for int() with base 10: 'привет'

# <center> Вычисления с NumPy массивами </center>

In [133]:
arr = np.array([[1.0,2.0,3.0], [4.0,5.0,6.0]])

In [134]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [135]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [136]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [137]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

$ x^2: $

In [138]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

$ x^{0.5} =  \sqrt{x}:$

In [140]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [143]:
arr2 = np.array([[5.0,3.0,0.0], [1.0,2.0,15.0]])

In [152]:
arr2

array([[ 5.,  3.,  0.],
       [ 1.,  2., 15.]])

In [153]:
arr2 > arr

array([[ True,  True, False],
       [False, False,  True]])

In [154]:
arr2 == arr

array([[False, False, False],
       [False, False, False]])

In [157]:
arr > arr2**2

array([[False, False,  True],
       [ True,  True, False]])